[env:adafruit_circuitplayground_m0]
platform = atmelsam
board = adafruit_circuitplayground_m0
framework = arduino
build_flags = -DUSB_VID=0x239A -DUSB_PID=0x8011 -DUSB_MANUFACTURER="Adafruit" -DUSB_PRODUCT="CPX"
